name: Publish reports

on:
  push:
    branches: [ main ]

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install coverage
    - name: Create coverage
      run: |
        coverage run -m unittest
        coverage xml -o cov.xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          files: ./cov.xml
          fail_ci_if_error: true

